DR-2437 Update 404 page
DataBiosphere/jade-data-repo-ui pull request #1098
Opened 2022-03-28 18:19 UTC by tlangs

Updating the 404 page with a fun new graphic! This PR simply the old 404 page. There is no change in behavior when a dataset/snapshot is not found. Those still render out a blank page with the error toast. If we want to change that behavior, we should consider a follow-on ticket.

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/3210510/160461356-fc315a8b-2930-4acc-9e5c-9e94c860881e.png">

2022-03-28 18:24 UTC, nmalfroy requested changes
Nice!  Another tsx file! You mind just creating the followon ticket for 404-ing if the dataset/snapshot isn't found?

2022-03-28 18:24 UTC, nmalfroy commented on src/routes/NotFound.tsx
> +          component={RouterLink}
I think you want to add `disableElevation`

2022-03-28 19:08 UTC, tlangs commented
I've created https://broadworkbench.atlassian.net/browse/DR-2511 as a follow on.

2022-03-29 12:27 UTC, snf2ye approved these changes

2022-03-29 12:27 UTC, snf2ye commented on src/routes/NotFound.tsx
> +import React from 'react';
Since this is a component, I think this file should live in components/common folder. But, probably still work re-visiting organization as a team.

2022-03-30 00:03 UTC, fboulnois approved these changes
neat! 📸

2022-04-07 15:41 UTC, nmalfroy approved these changes

2022-04-07 15:42 UTC, merged