DR-2474 Loading indicators for Dataset and Snapshot Views
DataBiosphere/jade-data-repo-ui pull request #1100
Opened 2022-03-29 16:57 UTC by tlangs

Added loading indicators on the Dataset and Snapshot tables of the Home view. I was able functionalize SnapshotTable, but trying to do the same to SnapshotView caused an infinite loop that I couldn't figure out how to prevent.

2022-03-29 17:30 UTC, snf2ye approved these changes

2022-04-01 15:15 UTC, nmalfroy requested changes
I'm not sure about the approach.  I was kinda thinking we might introduce a request object to wrap requests so that we can set loading status consistently.  Might be worth holding off on this one since it's right in the middle of a lot of the changes I'm doing around typescript

2022-04-01 15:15 UTC, nmalfroy commented on src/reducers/query.js
> +      [ActionTypes.GET_SNAPSHOTS]: (state) =>
I think that this is the wrong reducer.  This should be in the snapshots reducer I think.  Also, it's never getting unset on failure

2022-04-12 20:28 UTC, nmalfroy approved these changes
Looks great!  I think you just need to chance the dev dependency thing

2022-04-12 20:28 UTC, nmalfroy commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^5.18.0",
I think this should be a dev dependency

2022-04-12 22:49 UTC, merged