Otchet/dr 2711 patch dataset description in UI
DataBiosphere/jade-data-repo-ui pull request #1179
Opened 2022-09-12 21:00 UTC by otchet-broad

Adds dataset description editing to the UI.

Testing to see if a new PR handles the Cypress actions any better.

2022-09-13 16:06 UTC, otchet-broad commented
FYSA: This PR code is tailored to the implementation for datasets only.  For example, canEdit is computed inside of the DescriptionView component.  In DR-2712, this is refactored so the calculation of canEdit occurs on the resource using the description component.

2022-09-14 13:45 UTC, nmalfroy requested changes
Looks great!  My main thing is that the new component should use typescript

2022-09-14 13:45 UTC, nmalfroy commented on src/components/DescriptionView.jsx
> +const styles = (theme) => ({
given that this is a new component, could you make this a `tsx`?

2022-09-14 13:45 UTC, nmalfroy commented on src/components/DescriptionView.jsx
> +      errorDetail: 'Exceeds 2047 characters.  Please revise and save again.',
Might want to use the variable in here
```suggestion
      errorDetail: `Exceeds ${maxLength} characters.  Please revise and save again.`,
```

2022-09-14 13:45 UTC, nmalfroy commented on src/components/DescriptionView.jsx
> +const maxLength = 2047;
we typically snake case constants
```suggestion
const MAX_LENGTH = 2047;
```

2022-09-14 13:45 UTC, nmalfroy commented on src/components/DescriptionView.jsx
> +    this.state = {
We've been moving towards using React effects for components. More of an FYI. We can always convert it over afterwards but just as a heads up

2022-09-14 14:42 UTC, otchet-broad commented on src/components/DescriptionView.jsx
> +const styles = (theme) => ({
Refactoring now.

2022-09-14 17:17 UTC, otchet-broad commented on src/components/DescriptionView.tsx
> +  descriptionValue: string | null;
FYSA: nulls are refactored to undefined in DR-2712

2022-09-14 17:19 UTC, nmalfroy approved these changes
This looks great!  Thanks for the refactor

2022-09-14 17:19 UTC, nmalfroy commented on src/components/DescriptionView.tsx
> +      this.setState({ descriptionValue: newDescription.substring(0, 2046) });
should this be:
```suggestion
      this.setState({ descriptionValue: newDescription.substring(0, MAX_LENGTH - 1) });
```

2022-09-14 17:19 UTC, nmalfroy commented on src/components/DescriptionView.tsx
> +      <>
oh interesting: I've never seen this done with the empty bracket rather than arrays.  I like this

2022-09-14 17:46 UTC, otchet-broad commented on src/components/DescriptionView.tsx
> +      this.setState({ descriptionValue: newDescription.substring(0, 2046) });
Yes!  Good catch.  Thank you!

2022-09-14 18:56 UTC, okotsopoulos approved these changes
Great work on this!  I really appreciate how you took a ticket that was meant to be a simple entrypoint into our UI code and turned it into an opportunity to make thoughtful, tangible improvements.

A few meta-comments / preferences.

- Reviewing with the destination branch's commits interwoven through the diff view is a little confusing.  I *think* we tend to prefer merging rather than rebasing when bringing a feature branch up-to-date (@nmalfroy, please keep me honest if that's inaccurate).

- I find reviewing PRs easier when they contain fleshed-out descriptions, even if this context is redundant with what's in the ticket or what's been demoed in person.  [This article](https://mtlynch.io/code-review-love/) is a favorite of the team's, with technique 2 being relevant:

>Your changelist description should summarize any background knowledge the reader needs. You might have a code reviewer in mind when you write the description, but they don’t necessarily have the context you imagine. Besides, your other teammates might need to read this changelist as well, and readers in the future should understand your intentions when they look back on the change history.

2022-09-14 18:56 UTC, okotsopoulos commented on src/components/DescriptionView.test.tsx
> +describe('DescriptionView', () => {
I have little-to-no practical experience in this repo / UI technologies, I appreciate how easy to follow your tests are!

2022-09-14 20:17 UTC, merged