DR-638 Michael's big table refactor
DataBiosphere/jade-data-repo-ui pull request #137
Opened 2019-12-06 20:04 UTC by myessail

2019-12-16 19:21 UTC, myessail commented on src/components/dataset/query/QueryView.jsx
> -          SELECT * EXCEPT (${DB_COLUMNS.ROW_ID}) FROM \`${dataset.dataProject}.datarepo_${dataset.name}.${selected}\`
using this to assign the `key` property to each row in the table, but still hiding it from the user

2019-12-16 19:22 UTC, myessail commented on src/components/table/LightTable.jsx
> +export class LightTable extends React.PureComponent {
previously JadeTable

2019-12-17 17:57 UTC, thathert requested changes
🤶

2019-12-17 17:57 UTC, thathert commented on package.json
> -    "material-table": "^1.54.1",
Yayy

2019-12-17 17:57 UTC, thathert commented on src/components/table/JadeTable.jsx
> +      rowsPerPage: +event.target.value,
I used to do always do this, but found it's confusing to readers unfamiliar with the quirks of js. Better to do the less-cool-but-more-readable `parseInt`

2019-12-17 17:57 UTC, thathert commented on src/components/table/JadeTable.jsx
> +                    <TableRow hover tabIndex={-1} key={row.code}>
Why tabIndex -1

2019-12-17 17:57 UTC, thathert commented on src/components/table/JadeTableHead.jsx
> +                    direction={order !== '' ? order : 'desc'}
What about if order is null or undefined?

2019-12-17 17:57 UTC, thathert commented on src/modules/bigquery.js
> +      const columnId = _.get(column, 'id');
What does this gain us over using `column.id`? I can see usefulness in the cases where the properties are nested inside of the object, but this seems unnecessary.

2019-12-17 17:57 UTC, thathert commented on src/modules/bigquery.js
> +        res.code = value;
Why `code`?

2019-12-17 18:22 UTC, RoriCremer approved these changes

2019-12-17 19:42 UTC, thathert approved these changes
👍 LGTM

2019-12-17 19:44 UTC, merged