DR-1284 "snapshot full dataset" modal sharing view
DataBiosphere/jade-data-repo-ui pull request #711
Opened 2020-09-29 19:40 UTC by myessail

![snapfull](https://user-images.githubusercontent.com/5948715/94607576-19593e00-026a-11eb-9784-a6f59848acb6.gif)

2020-09-30 16:25 UTC, RoriCremer commented on src/components/dataset/details/CreateFullSnapshotNamingView.jsx
> +          Save snapshot
Do we also want this to be disabled if the snapshot name is already in use?

2020-09-30 16:26 UTC, RoriCremer approved these changes

2020-09-30 20:03 UTC, nmalfroy requested changes
Looks good.  I think the validator needs to be fixed and maybe check you're not rendering the create modal unnecessarily

2020-09-30 20:03 UTC, nmalfroy commented on src/components/dataset/details/CreateFullSnapshotNamingView.jsx
> +        <Button variant="contained" disabled={name === ''} onClick={setIsSharing}>
Is that really the only requirement?  What if it's `'    '` or do we allow slashes etc?  Is there a max length?  Looks like the server has a bunch of validation, e.g.:
```
pattern: '^[a-zA-Z0-9][_a-zA-Z0-9]*$'
minLength: 1
maxLength: 63
```
I'd:
a) rewrite this check with this in mind
b) move it to a function
c) Have it return what is wrong with the name in a human readable form and show that at least as a tooltip if not error text (is there room for that in the designs?

2020-09-30 20:03 UTC, nmalfroy commented on src/components/dataset/details/CreateFullSnapshotView.jsx
> +      {isSharing ? (
I'd wrap this whole thing with a check for `open` since, IIRC, even when it's closed, it tries to render the dialog contents. Might be worth double checking (throw a `console.log` in `CreateFullSnapshotNamingView.render` to make sure it's not hitting that when it's not showing)

2020-09-30 20:03 UTC, nmalfroy commented on src/components/dataset/details/CreateFullSnapshotNamingView.jsx
> +}) => {
Linter's not happy here. Maybe take out the return so we don't get spammed with this in other PRs

2020-10-01 18:34 UTC, myessail commented on src/components/dataset/details/CreateFullSnapshotView.jsx
> +      {isSharing ? (
verified that it's not trying to render, so i'm going to leave as-is

2020-10-02 16:53 UTC, nmalfroy requested changes
Couple small things

2020-10-02 16:53 UTC, nmalfroy commented on src/libs/utils.js
> +  return name.length > 1 && name.length <= 63 && name.match('^[a-zA-Z0-9][_a-zA-Z0-9]*$');
this should be `name.length >= 1`

2020-10-02 16:53 UTC, nmalfroy commented on src/components/dataset/details/CreateFullSnapshotNamingView.jsx
> +        <Button variant="contained" disabled={name === ''} onClick={validateNameAndProgress}>
disabled should probably be using the new function

2020-10-05 14:11 UTC, nmalfroy approved these changes

2020-10-05 14:39 UTC, merged